import { expect, test } from "@playwright/test";
/**
 * Every fixture slide is rendered in the harness, screenshotted, and scored
 * (SSIM) against the PNG that real PowerPoint exported for the same slide
 * (fixtures/powerpoint/, generated by scripts/export-powerpoint.ps1).
 *
 * Unlike the self-referential screenshot baselines in render.spec.ts, these
 * catch "we render it differently than PowerPoint", not just "we render it
 * differently than yesterday".
 *
 * Three measures are asserted against committed per-slide baselines
 * (specs/oracle-baselines/): whole-image SSIM, the worst tile's SSIM, and each
 * 4x3 region's painted coverage against PowerPoint's. See oracle.ts for why one
 * number cannot do this job, and for the fault injection that settled the
 * third. To (re)record after an intentional rendering change:
 *
 *   ORACLE_UPDATE=1 pnpm test   (or: pnpm test:oracle-update)
 *
 * Baselines are per platform, and a platform without them skips before doing
 * any work, so this whole spec is inert anywhere it has not been recorded.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";

import { ALL_DECKS } from "./decks";
import {
  INK_TOLERANCE,
  isUpdateMode,
  POWERPOINT_DIR,
  readScoreBaseline,
  SCORE_FLOOR,
  SCORE_TOLERANCE,
  scoreAgainstPowerPoint,
  TILE_TOLERANCE,
  writeScoreBaseline,
} from "./oracle";
import { openSlide, slideContainer } from "./utils";

for (const { name: deck, slides } of ALL_DECKS) {
  test.describe(`oracle: ${deck}`, () => {
    for (let slide = 0; slide < slides; slide++) {
      test(`slide ${slide + 1} matches PowerPoint output`, async ({ page }, testInfo) => {
        const project = testInfo.project.name;
        const baseline = readScoreBaseline(deck, slide, project);

        // Baselines are platform-specific (font and antialiasing differences
        // move SSIM by 0.01-0.03), so a platform without recorded ones has
        // nothing to compare against and skips instead of failing. Record with
        // "pnpm test:oracle-update" on that OS.
        //
        // Skipping here rather than after scoring matters: rendering every
        // slide and running SSIM over it is this spec's entire cost, and CI
        // runs on a platform with no baselines, so it was paying that in full
        // for a result it then threw away. The same slides were already being
        // skipped there, so this changes when we give up, not what is covered.
        // A blank or broken slide is still caught on every platform, by
        // exported-decks.spec.ts for the exported decks and by the screenshot
        // baselines in render.spec.ts and table-borders.spec.ts for the
        // generated ones. Neither needs an oracle baseline.
        test.skip(
          !isUpdateMode && baseline === null,
          `No oracle baseline for ${deck} slide ${slide} (${project}, ${process.platform})`,
        );

        const powerPointPath = join(POWERPOINT_DIR, deck, `slide-${slide}.png`);
        if (!existsSync(powerPointPath)) {
          throw new Error(
            `Missing PowerPoint export ${powerPointPath}. Run "pnpm oracle:export" on a machine with PowerPoint.`,
          );
        }

        await openSlide(page, `${deck}.pptx`, slide);
        const screenshot = await slideContainer(page).screenshot();
        const score = await scoreAgainstPowerPoint(screenshot, powerPointPath);

        if (isUpdateMode) {
          writeScoreBaseline(deck, slide, project, score);
          return;
        }

        // Absolute floor, in case a baseline was recorded from something
        // already broken.
        expect(
          score.overall,
          `SSIM vs PowerPoint fell below the absolute floor ${SCORE_FLOOR}: the slide is likely blank or badly broken`,
        ).toBeGreaterThanOrEqual(SCORE_FLOOR);

        // Narrowing only. A null baseline either skipped above or was just
        // written and returned, so this cannot be reached.
        if (baseline === null) return;

        expect(
          score.overall,
          `SSIM vs PowerPoint dropped below baseline ${baseline.overall} - ${SCORE_TOLERANCE}`,
        ).toBeGreaterThanOrEqual(baseline.overall - SCORE_TOLERANCE);

        expect(
          score.worstTile,
          `The worst tile dropped below baseline ${baseline.worstTile} - ${TILE_TOLERANCE}: ` +
            `some region of the slide regressed even if the slide as a whole still scores well`,
        ).toBeGreaterThanOrEqual(baseline.worstTile - TILE_TOLERANCE);

        // Per region, not worst-of: a region that permanently sits worst would
        // otherwise mask a different region losing its content entirely.
        const worst = score.ink.reduce(
          (found, drift, region) =>
            drift - baseline.ink[region] > found.excess
              ? { region, drift, excess: drift - baseline.ink[region] }
              : found,
          { region: -1, drift: 0, excess: -Infinity },
        );
        expect(
          worst.drift,
          `Region ${worst.region} of the 4x3 grid paints ${worst.drift.toFixed(3)} away from ` +
            `PowerPoint's coverage against a baseline of ${baseline.ink[worst.region]}: content ` +
            `there is missing, collapsed, or newly overflowing`,
        ).toBeLessThanOrEqual(baseline.ink[worst.region] + INK_TOLERANCE);
      });
    }
  });
}
