import { expect, test } from "@playwright/test";
/**
 * Ground-truth oracle specs.
 *
 * Every fixture slide is rendered in the harness, screenshotted, and scored
 * (SSIM) against the PNG that real PowerPoint exported for the same slide
 * (fixtures/ground-truth/, generated by scripts/export-ground-truth.ps1).
 *
 * Unlike the self-referential screenshot baselines in render.spec.ts, these
 * catch "we render it differently than PowerPoint" — not just "we render it
 * differently than yesterday".
 *
 * Scores are asserted against committed per-slide baselines
 * (specs/oracle-baselines/) and fail when a score drops by more than the
 * tolerance. To (re)record after an intentional rendering change:
 *
 *   ORACLE_UPDATE=1 pnpm test   (or: pnpm test:oracle-update)
 */
import { existsSync } from "node:fs";
import { join } from "node:path";

import { openSlide, slideContainer } from "./helpers";
import {
  GROUND_TRUTH_DIR,
  isUpdateMode,
  readScoreBaseline,
  SCORE_TOLERANCE,
  ssimAgainstGroundTruth,
  writeScoreBaseline,
} from "./oracle-helpers";

const DECKS: Array<{ deck: string; slides: number }> = [
  { deck: "basic", slides: 3 },
  { deck: "bom-rels", slides: 1 },
  { deck: "nested-charts", slides: 2 },
  { deck: "tables-groups", slides: 2 },
];

for (const { deck, slides } of DECKS) {
  test.describe(`oracle: ${deck}`, () => {
    for (let slide = 0; slide < slides; slide++) {
      test(`slide ${slide + 1} matches PowerPoint output`, async ({ page }, testInfo) => {
        const groundTruthPath = join(GROUND_TRUTH_DIR, deck, `slide-${slide}.png`);
        if (!existsSync(groundTruthPath)) {
          throw new Error(
            `Missing ground truth ${groundTruthPath}. Run "pnpm oracle:export" on a machine with PowerPoint.`,
          );
        }

        await openSlide(page, `${deck}.pptx`, slide);
        const screenshot = await slideContainer(page).screenshot();
        const score = await ssimAgainstGroundTruth(screenshot, groundTruthPath);

        const project = testInfo.project.name;
        if (isUpdateMode) {
          writeScoreBaseline(deck, slide, project, score);
          return;
        }

        const baseline = readScoreBaseline(deck, slide, project);
        if (baseline === null) {
          throw new Error(
            `No oracle baseline for ${deck} slide ${slide} (${project}). ` +
              `Record one with "pnpm test:oracle-update". Measured SSIM: ${score.toFixed(4)}`,
          );
        }

        expect(
          score,
          `SSIM vs PowerPoint dropped below baseline ${baseline} - ${SCORE_TOLERANCE}`,
        ).toBeGreaterThanOrEqual(baseline - SCORE_TOLERANCE);
      });
    }
  });
}
